### ISSUE TITLE
Clean production code

### ISSUE THREAD

**Issue by iegik** [andyhu/node-transliteration#10]
Problem:
Output code (transliteration.min.js) includes repeated require `...:[function(require,module,exports){module.exports = ...},{},]`, which can be squash into plain JavaScript.

Solution:
- https://www.npmjs.com/package/amdclean

**Comment by andyhu** [comment]
Hi, thanks for the spot. Could you please test against version 1.0?

**Comment by andyhu** [comment]
Close it for now. Need for more information. If you believe it's a bug please comment again. Thanks for your contribution!
