### ISSUE TITLE
chinese vs japanese

### ISSUE THREAD

**Issue by vampirefrog** [andyhu/node-transliteration#11]
Thanks for making this node module, it looks pretty neat, I've been looking for a separate transliterator, one that's not a web service, for a while now.

I'm trying to transliterate '古代祐三' to Yuzo Koshiro or Koshiroyūzō or at least koshiroyuzo, however, I'm getting the chinese transliteration:

```
> tr('古代祐三'); // Yuzo Koshiro, google translate gives Koshiroyūzō
'Gu Dai You San'
> tr('鈴木さると'); // Saruto Suzuki, google translate gives Suzuki saru to
'Ling Mu saruto'
```

Is there a way to prefer japanese over chinese?
Thanks!

**Comment by andyhu** [comment]
Hi! I'm glad that you found this module useful and thanks for bring this up. I have actually thought about this before. From my reasearch, I found two modules which can convert Japanese to Romaji:
https://github.com/WaniKani/WanaKana
https://github.com/hakatashi/japanese.js
Hope it would help

**Comment by vampirefrog** [comment]
Thanks, kuroshiro seems to come close to what I need.

**Comment by andyhu** [comment]
In the future I'm thinking to integrate something like kuroshiro with transliteration (if doable) or provide a database and / or pluggable rules in a middleware. But I'm not sure when I have time to do this (or probably I'll never have time :)). If there's any thought or suggestions please leave a comment. Thanks
