### ISSUE TITLE
ISO-9 Cyrilic Table1, Table2, Table3

### ISSUE THREAD

**Issue by iegik** [andyhu/node-transliteration#13]
[ISO-9](https://en.wikipedia.org/wiki/ISO_9) ([ru](https://ru.wikipedia.org/wiki/ISO_9)) for Cyrilic languages have at least 3 variants of translitiration.
To resolve this problem we can pass to the translation function argument with standard string, for example `ISO-9.Table1.ru` or `ISO-9.Table1.uk`

**Comment by andyhu** [comment]
Hi @iegik, thanks for reporting this. Could you elaborate more? Thanks
