### ISSUE TITLE
'abcd测试'转换结果为'abcdce-shi'？

### ISSUE THREAD

**Issue by wolfsilver** [andyhu/node-transliteration#2]
`abcd-ce-shi`应该更合理吧？

**Comment by andyhu** [comment]
的确，不过这个问题有点麻烦，需要检测中文和英文的分界。是不是可以在transliteration之前，先把中英文间加上空格？
str = str.replace(/([\u4e00-\u9fa5])([^\u4e00-\u9fa5\W])/g, '$1 $2').replace(/([^\u4e00-\u9fa5\W])([\u4e00-\u9fa5])/g, '$1 $2')

**Comment by Wolfsilver** [comment]
测试ABC
会转换为
ce-shi- ABC

**Comment by andyhu** [comment]
此问题在1.0版本已修复

**Comment by andyhu** [comment]
1.0版本已更新到npm和bower
