### ISSUE TITLE
Is there way to reverse transliteration string to its origin ?

### ISSUE THREAD

**Issue by HarDGraD** [andyhu/node-transliteration#20]
Hello!

I need to transliterate some string and then get origin string from this transliterated string. Is there way to do it ?

Thanks in advance for your reply!

**Comment by andyhu** [comment]
Hi @HarDGraD,

As far as I know it's quite hard to say. It depends on the specific languages you'd like to transliterate.
I'll take two examples.
`tu` and `tú` in Spanish do not mean the same thing, but they are both translated into `tu`.
`上海` in Chinese means Shanghai (city) and is translated into `Shang-Hai`, but it also could be `伤害` (hurt).

Hope it helps.

**Comment by HarDGraD** [comment]
Thank you for reply.

Yes. You are right. I will choose another way to resolve my problem.
