### ISSUE TITLE
Does not work inside web workers

### ISSUE THREAD

**Issue by glueball** [andyhu/node-transliteration#21]
Importing the transliteration module in the context of a Web Worker does not work as expected.

```
  self.importScripts('/js/libs/transliteration.min.js');
  var t = transl("This line throws error");
```

I believe this has to do with the fact that there is no window object defined in the web worker context.

**Comment by andyhu** [comment]
Hi @glueball,
Thanks for using the module, it's been fixed in v1.1.15. Let me know if there's still any issues.

Cheers
