### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by adamterlson** [andyhu/node-transliteration#23]
I am trying to include transliteration in my React Native app.  I am having difficulties because the transliterate.js file[does dynamic module loading](https://github.com/andyhu/node-transliteration/blob/master/lib/node/transliterate.js#L94):

```
codemap[offset] = require('../../data/x' + offset.toString(16) + '.json');
```

This fails in React Native because [the RN packager does not support dynamic module loading](https://github.com/facebook/react-native/issues/6391).

Is there any hope of using this package on React Native?  Is there an easy way to bundle up all required assets (including all the JSON files that are dynamically required) perhaps and add a RN version?

Thanks for any thoughts you have!

**Comment by andyhu** [comment]
Thanks for using the module, I may need to refactor the module a bit to by pass dynamic module loading. Will let you know when it's finished

**Comment by andyhu** [comment]
Hi @adamterlson,
Did you try to import from `transliteration/lib/browser/transliteration`? I believe the browser version of the module doesn't have any dynamic module loading. However if it still doesn't work, please let me know.

**Comment by adamterlson** [comment]
Hey thanks for the quick response!  

I tried it, but React Native supports [ES6 module syntax](https://facebook.github.io/react-native/docs/javascript-environment.html) and doesn't have AMD or common modules.

**Comment by andyhu** [comment]
It should be working with React Native now with v1.2.0
`import { transliterate, slugify } from 'transliteration/src/main/browser';`

**Comment by adamterlson** [comment]
Thank you @andyhu for your super fast help!
