### ISSUE TITLE
Some characters are not transliterated

### ISSUE THREAD

**Issue by logical-and** [andyhu/node-transliteration#3]
Thanks for your library. I use it to send SMS about servers crash, and I found that sms delivered with longer that it should. It happened, because some characters not converted from UTF-8 to proper ASCII. Here is my fix in wrapper around your library.

![image](https://cloud.githubusercontent.com/assets/1403109/8510903/fe3eea6c-2307-11e5-9751-d310e3cf3f48.png)

Please submit, is it an issue with your library?

**Comment by andyhu** [comment]
Hi, sorry for the very late reply. What's the input and output for your test? I'll investigate it if you provide some test data

**Comment by andyhu** [comment]
Hi, since 1.0.x transliteration module support custom replace map. Hope it helps
