### ISSUE TITLE
This is a romanization library

### ISSUE THREAD

**Issue by amundo** [andyhu/node-transliteration#6]
Hi, 

Cool library. But isn’t it more accurate to call it a romanization library than a transliteration library? The term transliteration doesn’t assume a roman-alphabet output.

**Comment by andyhu** [comment]
Hi, yes you are probably right. Actually this module is inspired by the Drupal module with the same name transliteration and it's already published onto npm. I'll just keep it as it is until it's really necessary to change it. But thanks for being interested with the module
