### ISSUE TITLE
Bower build is broken

### ISSUE THREAD

**Issue by genixpro** [andyhu/node-transliteration#8]
The build that has been uploaded to Bower appears to be completely broken. When I download it and install it according to the documentation, I get an error that require is undefined. It seems like the node.js version may have been uploaded instead of the Bower version.

Also, it appears that that the regular JS file is minified - all of the code is on a single line. 

Also, it appears that the bower version 0.1.1 for this library has completely disappeared, which has prevented us from reverting to an old version without manually embedding the library into our own source code.

Several things appears to be wrong with the bower build.

**Comment by andyhu** [comment]
Hi, thanks for the info. I'll temporary recover to the old version and fix it later before pushing to git hub

**Comment by genixpro** [comment]
Thanks Andy for such a prompt response. We were about hack the shit out of our deployment process in order to get it to work.

**Comment by genixpro** [comment]
Would you be able to add in tags on your repository for the builds while your at it? This would allow us to install specific versions of node-transliteration and ensure that they are fixed, instead of always installing the latest. Right now if I try to install 0.1.x for instance, even right now after you reverted back and I know that 0.1.1 is there, I get the following:

bower transliteration#0.1.x not-cached git://github.com/andyhu/node-transliteration.git#0.1.x
bower transliteration#0.1.x    resolve git://github.com/andyhu/node-transliteration.git#0.1.x
bower transliteration#0.1.x     ENORESTARGET No tag found that was able to satisfy 0.1.x

Additional error details:
No versions found in git://github.com/andyhu/node-transliteration.git

**Comment by andyhu** [comment]
Thanks I'll do it

**Comment by andyhu** [comment]
I've added a release. Can you please test?

**Comment by genixpro** [comment]
Thanks Andy,

It seems to work now - when I use 0.1.x, it now correctly resolves to 0.1.1
from bower. If I use 0.2.x though, it tells me it can't find anything. I
presume your still working on fixing the 0.2.x series. However, my builds
are back to working, so we are happy. Thanks Andy! And thanks for writing
this library, its really helped us out with our searching functionality.

------
Bradley Arsenault < bradley.allen.arsenault@gmail.com >
647-261-0462
Toronto, Ontario

**Comment by andyhu** [comment]
Hi, just for your info, transliteration module has been updated to v1.0.x with 100% test coverage and added more functionality.
