### ISSUE TITLE
Transliterate Removal of Symbols

### ISSUE THREAD

**Issue by mayvn10** [andyhu/node-transliteration#9]
I am trying to transliterate ®, ©, ', and ™ into blank characters meaning completely removing them when they are slugified.

The following is what I tried to do:

```
var tr = require('transliteration');
var slugify = require('transliteration').slugify;

// replacement attempt
tr("0xAE, 0xFEFF"); // ®
tr("0xA9, 0xFEFF"); // ©
tr("0x2122, 0xFEFF"); // ™

slugify(name, { lowercase: true })
```

For example, when I use slugify on a name like "ABC®: 123", it transliterates to:
`abc-r-123
`

However, I want the resulting name to be like:
`abc-123`

**Comment by andyhu** [comment]
Hi, it's a bit difficult to do in this library since I don't have the range of special characters which need to be removed. Can you please try to remove those characters before using slugify?
`javascript
str = tr(str.replace(/®©™/g, ''))
`

**Comment by mayvn10** [comment]
it wasn't working this way. instead, i had to do this to replace it:

`tr(name).replace(/\((r)\)|\((c)\)|\((tm)\)|®|©|™|'|ʼ/g, '');`
